version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo-chronos
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chronos
      MONGO_INITDB_ROOT_PASSWORD: chronos
      MONGO_INITDB_DATABASE: chronos
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
